#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Allow CTRL-S in terminal Vim
stty -ixon
#Aliases
if [ -f ~/.dotfiles/aliases_rakuten ]; then
    . ~/.dotfiles/aliases_rakuten
fi
